# Generated by Django 5.1.6 on 2025-02-23 04:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('ongoing', '進行中'), ('win', '勝利'), ('lose', '敗北'), ('draw', '引き分け')], default='ongoing', max_length=20, verbose_name='対局結果')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='対局開始時刻')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='対局終了時刻')),
                ('board_state', models.TextField(blank=True, help_text='盤面の状態をJSON形式などで保存（任意）', null=True, verbose_name='盤面状態')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL, verbose_name='先手プレイヤー')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL, verbose_name='後手プレイヤー')),
            ],
        ),
    ]
