# Generated by Django 5.1.6 on 2025-02-26 14:32

import matches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_gamestate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='turn',
            field=models.CharField(choices=[('sente', '先手'), ('gote', '後手')], default='sente', max_length=10),
        ),
        migrations.AlterField(
            model_name='gamestate',
            name='pieces_in_hand',
            field=models.JSONField(default=matches.models.initial_pieces_in_hand),
        ),
    ]
