# Generated by Django 5.1.6 on 2025-03-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_player2_alter_match_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='last_move',
            field=models.JSONField(default=list),
        ),
    ]
