# Generated by Django 5.1.6 on 2025-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_result_undorequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='allow_undo',
            field=models.BooleanField(default=True),
        ),
    ]
