# Generated by Django 5.1.6 on 2025-02-23 04:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kifu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moves', models.TextField(help_text='対局の指し手をJSON形式などで保存', verbose_name='指し手データ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日時')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kifu', to='matches.match', verbose_name='対局')),
            ],
        ),
    ]
